Fix vde_cryptcab so it compiles under MacOS
virtualsquare/vde-2 pull request #43
Opened 2023-04-15 19:15 UTC by jguillaumes

I hope 3 will be my lucky number.
See commit messages for details.

2023-04-16 04:16 UTC, danielinux requested changes
Please check indentation

2023-04-16 04:17 UTC, danielinux commented
One last thing, please check the indentation of your code (memset and od= lines)

2023-04-16 14:02 UTC, danielinux reviewed
Sorry for being pedantic about indentation. vde-2 uses tabs not spaces please fix the spacing of the od = line as suggested

2023-04-16 14:02 UTC, danielinux commented on src/vde_cryptcab/vde_cryptcab_client.c
> +    od = mkostemps(keyname, 4, O_EXLOCK);
Should be tab not spaces
```
	memset(keyname + strlen(keyname) - 10, 'X', 6);
#ifdef VDE_DARWIN
	od = mkostemps(keyname, 4, O_EXLOCK);
#else
	od = mkostemps(keyname, 4, O_RDWR | O_CREAT | O_TRUNC);
#endif
```

2023-04-18 06:29 UTC, jguillaumes commented
Oh well... 
I'm in a conference now, will fix it next weekend

2023-04-22 04:19 UTC, danielinux commented
Closing, replaced by #45

2023-04-22 04:19 UTC, closed without merging